version: '3.8'

networks:
  ela-network:
    name: ela-network
    driver: bridge

services:

  backend-service:
    build: .
    image: backend-service
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 30s
      timeout: 5s
    restart: always
    networks:
      - ela-network
    ports:
      - "8080:8080"